### ISSUE TITLE
virtue fails trial doesn't oh no

### ISSUE THREAD

**Issue by Julian** [Julian/Virtue#11]
```
⊙  t jsonschema.tests.test_jsonschema_test_suite.TestDraft6.test_ipv6_validation_of_IPv6_addresses_zone_id_is_not_a_part_of_ipv6_address                                                          julian@Air
Traceback (most recent call last):
  File "/Users/julian/.dotfiles/.local/share/virtualenvs/jsonschema/lib/python3.9/site-packages/virtue/locators.py", line 98, in locate_by_name
    return self.locate_in(obj)
  File "/Users/julian/.dotfiles/.local/share/virtualenvs/jsonschema/lib/python3.9/site-packages/virtue/locators.py", line 122, in locate_in
    raise ValueError(
ValueError: Can't determine the appropriate way to load <function _Test.to_unittest_method.<locals>.fn at 0x1074fbdc0>
```

(where that test method is dynamically generated in jsonschema's test suite)

But trial loads that just fine.

**Comment by Julian** [comment]
Closed via 8964120.
